### PR TITLE
Chore refactor events

### PR DESCRIPTION
**Pull request by e-schultz**
Got carried away with a little bit of refactoring. My initial intent was to push events to a more appropiate location, then sort of snowballed from there.

Tried to keep each commit focused, and a longer detailed explanation to what/why. The core of what you had is still very much the same, just with a bit of massaging. 

For an app this small, may be a bit overkill. But as apps grow, and you start doing unit testing/TDD - it will make your life easier in the long run.

### CODE REVIEW

**Comment by nehero** [comment]
Hey thanks a ton for that! I agree, it was very messy and you cleaned it up quite nice. Curious though, why did you create an instance of 'this' into the variable 'vm'?

**Comment by e-schultz** [comment]
Basically has to do with the scope of 'this' with callbacks in JavaScript.
If there was

```javascript
this.name = 'Fred'
this.changeName = function(newName) {
   this.name = newName
}
```

and in the view, had

```html
<button ng-click="ctrl.changeName('Hello')">
```

'this' isn't pointing to what you think it is. By doing  var vm=this, then
using vm. throughout - inside of the function,, it has a reference to the
'vm' variable.

A more concrete example that you could copy/paste into your console

```javascript
function BobCtrl() { this.name = 'Bob'; this.setName = function(newName) {
this.name = newName; } this.sayName = function() { console.log(this.name);
} }
var bob = new BobCtrl();
bob.sayName(); // outputs 'Bob'
bob.setName.apply(null,['Bob Barker']);
bob.sayName(); // still outputs 'Bob'

function FredCtrl() { var vm = this;
vm.name = 'Fred'; vm.setName = function(newName) { vm.name = newName;
} vm.sayName
= function() { console.log(vm.name); }
}
var fred = new FredCtrl();
fred.sayName(); // outputs fred
fred.setName.apply(null,['Fred Flintstone']);
fred.sayName(); // outputs Fred Flintstone
```

When dealing with event callbacks, etc - it's doing a .apply on setName and
not just calling setName, so it can be hard to know what the context of
'this' is, (in this case, I passed in null).

Another example

```javascript
var person = { name: 'Whats going on' };

function BobCtrl() { this.name = 'Bob'; this.setName = function(newName) {
this.name = newName; } this.sayName = function() { console.log(this.name);
} }
var bob = new BobCtrl();
bob.sayName(); // outputs 'Bob'
bob.setName.apply(person,['Bob Barker']);
bob.sayName(); // still outputs 'Bob'
console.log(person.name); // person.name is now 'Bob Barker', because in
that function, 'this' is pointing to person

var person2 = { name: 'Person 2'};
function FredCtrl() { var vm = this;
vm.name = 'Fred'; vm.setName = function(newName) { vm.name = newName;
} vm.sayName
= function() { console.log(vm.name); }
}
var fred = new FredCtrl();
fred.sayName(); // outputs fred
fred.setName.apply(person2,['Fred Flintstone']);
fred.sayName(); // outputs Fred Flintstone
console.log(person2.name); // still 'Person 2';
```

by following the var vm = this pattern, it helps ensure that 'this' is
pointing to what you really expect it to.

This is solved with ES6 and arrow functions, but that's a whole other thing
to get into.

**Comment by nehero** [comment]
Thanks that really helped! So would this essentially replace the need for $scope?

**Comment by e-schultz** [comment]
Yep,

In most of the newer style guides, and even as part of the Angular
documentation - they are really recommending away from relying on $scope.
There are a few times of which it can't be avoided, but it's a concept that
is getting axed in Angular 2.0 - so the less you have it scattered around
your code, the more prepared you will be for Angular 2.

$scope ends up getting into the prototypal inheritance chain, which lends
people to want to do things like $scope.parent.x (if they have nested
controllers), which then ends up getting really brittle.

About the only time I use $scope now, is if I'm binding to events (I have
my own event emitter that is not based on $rootScope, but a very similar
pattern to what I sent in the PR) - and I need to unbind them when the
controller gets destroyed.

I generally avoid $scope.$watch/etc also - as there are generally other and
better ways of handling things, which can usually be done through other
ways (ie: ng-change, or user actions to trigger things).

$scope.$watch can quickly get out of hand - especially if $scope.$watch
modifies another object/property that also has a $scope.$watch, and next
thing you know you have watches triggering other watches triggering the
first watch - and a big circle of stuff going on that gets very difficult
to understand what's going on.

**Comment by nehero** [comment]
I can definitely see why that makes sense now. Thanks a lot for the help!

**Pull request merged**
